    create table contato (
       id bigint generated by default as identity,
        ativo boolean,
        nome varchar(255),
        primary key (id)
    )
    create table contato_fone (
       id bigint generated by default as identity,
        ativo boolean,
        fone varchar(255),
        obs varchar(255),
        contato_id bigint,
        primary key (id)
    )

    alter table contato_fone 
       add constraint FK41uff566q4jfp1iwiu5hh6ju8 
       foreign key (contato_id) 
       references contato